/*
 * This class was auto-generated from the API references found at
 * https://epayments-api.developer-ingenico.com/s2sapi/v1/
 */
namespace Ingenico.Connect.Sdk.Domain.Payment.Definitions
{
    public class PaymentReferences
    {
        /// <summary>
        /// Your order ID for this transaction that is also returned in our report files
        /// </summary>
        public long? MerchantOrderId { get; set; } = null;

        /// <summary>
        /// Your unique reference of the transaction that is also returned in our report files. This is almost always used for your reconciliation of our report files.
        /// </summary>
        public string MerchantReference { get; set; } = null;

        /// <summary>
        /// Payment Reference generated by WebCollect
        /// </summary>
        public string PaymentReference { get; set; } = null;

        /// <summary>
        /// Provides an additional means of reconciliation for Gateway merchants
        /// </summary>
        public string ProviderId { get; set; } = null;

        /// <summary>
        /// Provides an additional means of reconciliation for Gateway merchants
        /// </summary>
        public string ProviderReference { get; set; } = null;

        /// <summary>
        /// When you did not supply a merchantReference for your payment, you need to fill this property with the reference of the original payment when you want to refund it
        /// </summary>
        public string ReferenceOrigPayment { get; set; } = null;
    }
}
