/*
 * This class was auto-generated from the API references found at
 * https://epayments-api.developer-ingenico.com/s2sapi/v1/
 */
namespace Ingenico.Connect.Sdk.Domain.Payment.Definitions
{
    public class SdkDataInput
    {
        /// <summary>
        /// Device information gathered by the 3DS SDK on a customer device. This is JSON name/value pairs that as a whole is Base64url encoded.
        /// </summary>
        public string DeviceInfo { get; set; } = null;

        /// <summary>
        /// Object containing rendering options of the device.
        /// </summary>
        public DeviceRenderOptions DeviceRenderOptions { get; set; } = null;

        /// <summary>
        /// Universally unique ID created upon all installations and updates of your app on a c Device. This will be newly generated and stored by the 3DS SDK for each installation or update
        /// </summary>
        public string SdkAppId { get; set; } = null;

        /// <summary>
        /// JWE Object containing data encrypted by the 3-D Secure SDK
        /// </summary>
        public string SdkEncryptedData { get; set; } = null;

        /// <summary>
        /// Public key component of the ephemeral key pair generated by the 3-D Secure SDK and used to establish session keys between the 3-D Secure SDK and ACS.
        /// </summary>
        public string SdkEphemeralPublicKey { get; set; } = null;

        /// <summary>
        /// Indicates maximum amount of time (in minutes) for all exchanges. Minimum amount of minutes is 5.
        /// </summary>
        public string SdkMaxTimeout { get; set; } = null;

        /// <summary>
        /// Identifies the vendor and version for the 3-D Secure SDK that is integrated in your app, assigned by EMVCo when the 3-D Secure SDK is approved.
        /// </summary>
        public string SdkReferenceNumber { get; set; } = null;

        /// <summary>
        /// Universally unique transaction identifier assigned by the 3-D Secure SDK to identify a single transaction.
        /// </summary>
        public string SdkTransactionId { get; set; } = null;
    }
}
