/*
 * This class was auto-generated from the API references found at
 * https://epayments-api.developer-ingenico.com/s2sapi/v1/
 */
namespace Ingenico.Connect.Sdk.Domain.Dispute.Definitions
{
    public class DisputeReference
    {
        /// <summary>
        /// The merchant&#8217;s order ID of the transaction to which this dispute is linked.
        /// </summary>
        public string MerchantOrderId { get; set; } = null;

        /// <summary>
        /// Your (unique) reference for the transaction that you can use to reconcile our report files.
        /// </summary>
        public string MerchantReference { get; set; } = null;

        /// <summary>
        /// Payment Reference generated by WebCollect.
        /// </summary>
        public string PaymentReference { get; set; } = null;

        /// <summary>
        /// The numerical identifier of the Service Provider (Acquirer).
        /// </summary>
        public string ProviderId { get; set; } = null;

        /// <summary>
        /// The Service Provider&#8217;s reference.
        /// </summary>
        public string ProviderReference { get; set; } = null;
    }
}
